### ISSUE TITLE
What SSIM parameters were used in the paper?

### ISSUE THREAD

**Issue by jkulhanek** [google-research/multinerf#108]
Hi,
Thank you for the great work!

Can you give more details on the exact evaluation parameters used in the paper? What implementation of SSIM with what parameters was used? Also, what was the resolution at which the images were compared?

Thank you.

**Comment by jonbarron** [comment]
The SSIM implemention is from dm_pix, and uses its default parameters: https://github.com/deepmind/dm_pix/blob/6f2cb67fe68b69f2084d833a59ab397c23f3f92f/dm_pix/_src/metrics.py#L125

The outdoor scenes were downsampled by 4x and the indoor scenes were downsample by 2x.

**Comment by jkulhanek** [comment]
Thank you very much for your quick response!
