### ISSUE TITLE
Could you please provide the version of jax, jaxlib and flax used in this repository?

### ISSUE THREAD

**Issue by zhangtianjia** [google-research/multinerf#11]
Very thankful for your impressive work in implementing the NeRF-based methods. However, when I was training the network, I encountered the problem of incompatibility. The usage of some functions is changed in the new version, such as jax and flax. May I know the installed version of jax, jaxlib, and fax?

**Comment by jonbarron** [comment]
We used the most recent public versions of all three libraries. Can you tell us more about the incompatibility issues you're having?

**Comment by zhangtianjia** [comment]
> We used the most recent public versions of all three libraries. Can you tell us more about the incompatibility issues you're having?

Thanks for your reply. In the beginning, I had python 3.6 installed. But the recent versions of jax, jaxlib, and flax do not support python 3.6. After I upgraded to python 3.8, the issues are overcomes. 
Thanks for your work.
