### ISSUE TITLE
DNN library is not found

### ISSUE THREAD

**Issue by shangyuna** [google-research/multinerf#14]
![image](https://user-images.githubusercontent.com/32950936/184053034-16d23e22-ec07-4a90-9d14-2ce323debfb8.png)
Python version：3.9.12
CUDA version：11.3.109
CUDNN version：8.2.4
jax version: 0.3.15
jaxlib version: 0.3.15+cuda11.cudann82
GPU: RTX 3070

**Comment by bmild** [comment]
I ran into the same issue and solved it by [installing CUDNN](https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#download).

**Comment by shangyuna** [comment]
I have installed CUDNN ，version：8.2.4

**Comment by shangyuna** [comment]
> I ran into the same issue and solved it by [installing CUDNN](https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#download).

I have installed CUDNN ，version：8.2.4

**Comment by shangyuna** [comment]
> I ran into the same issue and solved it by [installing CUDNN](https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#download).

I have installed CUDNN ，version：8.2.4

**Comment by theFilipko** [comment]
It works with cudnn 8.2 only
