### ISSUE TITLE
 How can I generate the kind of continuous 360° poses video like on the website?

### ISSUE THREAD

**Issue by zhangkai0425** [google-research/multinerf#15]
Thank you for the code of mipnerf-360!I wonder if there is a way to generate a continuous 360° poses video like on the website？I found that the render_360.sh script can only generate images in the test dataset.

**Comment by shangyuna** [comment]
for reference：
https://github.com/NVlabs/instant-ngp/blob/master/docs/nerf_dataset_tips.md
video：data-folder$ python [path-to-instant-ngp]/scripts/colmap2nerf.py --video_in <filename of video> --video_fps 2 --run_colmap --aabb_scale 16
images：data-folder$ python [path-to-instant-ngp]/scripts/colmap2nerf.py --colmap_matcher exhaustive --run_colmap --aabb_scale 16

**Comment by zhangkai0425** [comment]
Thank you!

**Comment by bmild** [comment]
Simple change the following flags to the render script to get a smoother video:

```
  --gin_bindings="Config.render_path_frames = 480" \
  --gin_bindings="Config.render_video_fps = 60" \
```

**Comment by zhangkai0425** [comment]
Thank you bmild!You really solved my problem.
