### ISSUE TITLE
Request for Active Dataset Download Link for RawNeRF

### ISSUE THREAD

**Issue by KimDomiz** [google-research/multinerf#161]
I am interested in studying your research on NeRF in the Dark. However, I was unable to download the dataset from the link provided on the RawNeRF site (https://bmild.github.io/rawnerf/) as it has expired. Could you please provide an active download link for the RawNeRF dataset?

**Comment by fhahlbohm** [comment]
Just copy the link address ;) http://storage.googleapis.com/gresearch/refraw360/raw.zip

**Comment by KimDomiz** [comment]
It's working! Thank you.
