### ISSUE TITLE
MipNeRF360 dataset link doesn't work

### ISSUE THREAD

**Issue by scymz2** [google-research/multinerf#165]
The link of the main dataset is no longer working, can you provide a new one please?

**Comment by jonbarron** [comment]
The links on https://jonbarron.info/mipnerf360/ work for me, can you point
me to the dead links you're seeing?

**Comment by scymz2** [comment]
Thank you for replying. 
I can download dataset part2, but when trying to download dataset part1, the browser shows an error indicating that it cannot be downloaded securely. Even after disabling the security mode, I am still unable to download it. This is the link I saw when I was trying to download the part1: http://storage.googleapis.com/gresearch/refraw360/360_v2.zip I tried on my two laptops and met the same problem.

**Comment by henry0523ho** [comment]
I have same issue too. But I found out that changing my browser from chrome to edge works from me.
