### ISSUE TITLE
About training time

### ISSUE THREAD

**Issue by StarsTesla** [google-research/multinerf#17]
Hi there, I downloaded the code and installed the dependecy, I use the 360_v2/room dataset for training, and I found the training time is extremely long.
I train use the original train_360 shell script in the code, only changed the data_dir and result dir.
I recall the paper says the Mip-NeRF 360 should 2x slow compared to the original NeRF or Mip-NeRF. and I trained the mip-nerf_pl which is the pytorch lighting version, and it took almost 20-30 hrs on single 3090 GPU 24GB, but this code of Mip-NeRF 360, I trained on 4 3090 GPU 24GB, it takes 3mins-4mins per 100 steps, for 250k steps, it should be over 120hrs, and that's around a week time, I wonder why is the training speed got that? Jax version I beileve should be faster than pytorch version.

**Comment by StarsTesla** [comment]
Sorry about that, I just ask server provider solve the problem，the speed have already up to 53552 r/s from recent 8400 r/s , which will takes 20hrs for the training process, thanks for the research you have made for us!

**Comment by theFilipko** [comment]
Hello. What are the ways to speed up the training? I have the latest version of the repo running the 'train_360.sh' script on a single GPU RTX3090 24GB, batch size 4096. It does 6300 r/s, in other words, 100 steps per minute. Thanks
