### ISSUE TITLE
[MipNeRF 360] Comparison to MipNeRF and NeRF

### ISSUE THREAD

**Issue by Totoro97** [google-research/multinerf#21]
Hi Thanks a lot for this project!

I have a dumb question on the comparisons to MipNeRF and NeRF.

![image](https://user-images.githubusercontent.com/6695053/185550552-ea93bce8-3785-4700-be30-b003fa37c297.png)

Does this sentence mean that the inputs of (Mip)NeRF are only the positional encoding, without the original xyz coordinates?

Thanks in advance!

**Comment by jonbarron** [comment]
Yes, that's right.
