### ISSUE TITLE
NaN weights in the begining of training

### ISSUE THREAD

**Issue by CSU-NXY** [google-research/multinerf#22]
Hi, thanks for your great work. I noticed that the weights would be NaN after the first sampling, however the training pipeline does not broken and the PSNR is growing. I'm wondering why this happened and how do you deal with NaN weights?
![image](https://user-images.githubusercontent.com/19389655/185566220-c6b2dd19-e6fd-4fbf-bdd1-38593fd4fd64.png)

**Comment by jonbarron** [comment]
That's pretty weird, and shouldn't happen. What are you running? Did you modify the code?

**Comment by CSU-NXY** [comment]
I'm running the [pinecone](https://drive.google.com/drive/folders/128yBriW1IG_3NJ5Rp7APSTZsJqdJdfc1) dataset using train_360.sh. The only changes I made are setting config.factor to 8 and config.batch_size to 1024 in 360.gin. 

I'm wondering whether the NaN comes from the sanity checking step in Jax, because the output looks good after the very first forward step.
![image](https://user-images.githubusercontent.com/19389655/186168149-413574b0-c81c-4326-8ed7-18caed46b31a.png)

**Comment by PaiDii** [comment]
Can you provide a link to the baidudisk of the pinecone dataset? The original link is not working. Thank you！
