### ISSUE TITLE
How to choose raydist_fn

### ISSUE THREAD

**Issue by CSU-NXY** [google-research/multinerf#25]
Hi, I'm using my own dataset in which `near=1e-4` and `far=5`. I noticed that when using `jnp.reciprocal` as `Model.raydist_fn`, almost all sample points are mapped to a small range around `0`.
![image](https://user-images.githubusercontent.com/19389655/186170220-362df741-2cfc-4a39-b51b-2a55a09c5458.png)

If I set `near=2` and `far=6`, the mapping result seems much reasonable. 
![image](https://user-images.githubusercontent.com/19389655/186171460-9b56d122-1b6a-425f-9019-74560606c652.png)

Since there are five mapping functions provided in `construct_ray_warps`, how can I choose the most appropriate one for my dataset?

**Comment by jonbarron** [comment]
I think this is something of an open research question. I'd just try a few and see which works best.

**Comment by bmild** [comment]
I would recommend `"piecewise"` in the case where you need to set the near value to 0 or something very small.

**Comment by CSU-NXY** [comment]
@bmild @jonbarron Thanks for quick reply.  `piecewise` works perfect for me! The mapping results seems quite good now.
![image](https://user-images.githubusercontent.com/19389655/186303910-7f8233ef-69e2-4180-8c56-7d15389ea6df.png)
