### ISSUE TITLE
Recommended hardware?

### ISSUE THREAD

**Issue by Palisand** [google-research/multinerf#40]
As expected, training MultiNeRF on my laptop (specs below) takes ages. After an hour, I still hadn't made it past the first checkpoint with the default configuration. I'd like to train on more capable hardware, like some beefy AWS instance. What do you recommend?

macOS Monterey
MacBook Pro 2018
Processor: 2.7 GHz Quad-Core Intel Core i7
Memory: 16 GB 2133 MHz LPDDR3
Graphics: Intel Iris Plus Graphics 655 1536 MB

**Comment by jonbarron** [comment]
For our papers we trained on Google TPUs (v2), but a desktop with a 3090 should be fine. I would not expect any laptop to be able to train well.

**Comment by Palisand** [comment]
Thanks.
