### ISSUE TITLE
jaxlib.xla_extension.XlaRuntimeError: UNIMPLEMENTED: DNN library is not found.

### ISSUE THREAD

**Issue by yao990113** [google-research/multinerf#52]
I have jax 0.3.17 and jaxlib 0.3.15 for cudnn82+cuda11. , my version of cudnn is 8.2.0 , but I still have problem as title ,can you help me?
thank you

**Comment by za970120604** [comment]
hello , @yao990113  , may I ask how did you solve this problem?
