### ISSUE TITLE
Ref-NeRF: bottleneck_noise value and effect

### ISSUE THREAD

**Issue by gkouros** [google-research/multinerf#60]
Hi,

I have a question regarding the value of bottleneck_noise for Ref-NeRF. In the paper, Appendix C, you mention that it is set to 0.1 which stabilizes the results. However, in the code it is 0 by default and not adapted to 0.1 in the refnerf config file. Was that intentional?

Also, what's the effect of setting it to 0 and not preventing the network from using the bottleneck early in training? Does it prevent the optimization of the roughness, tint etc?

Thank you in advance!

**Comment by dorverbin** [comment]
In the implementation used for generating the results of the paper, which was based on the mip-NeRF codebase, setting the bottleneck noise parameter to 0.1 worked slightly better. This was especially useful for the `ball` scene, where it prevented the network from getting stuck at a local minimum in the appearance model. In the MultiNeRF codebase, the behavior is slightly different, and we found that zero worked a little better in terms of quantitative performance (but it didn't really make much of a difference).

Hope this helps!

**Comment by gkouros** [comment]
Thank you for the thorough explanation!
